name: deeplabcut
channels:
  - pytorch
  - conda-forge
  - rapidsai-nightly
dependencies:
  - cudatoolkit=11.8.*
  - ipykernel
  - python=3.10.*
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-lightning
  - opencv
  - jupyterlab-nvdashboard
  - mlflow
  - pytables==3.8.0
